config/routes.rb
Spree::Core::Engine.add_routes do
  # Add your extension routes here
  namespace :admin do
    resources :contacts
    resources :newsletters

    get '/contact_settings', to: 'contacts#settings', as: 'contact_settings'
    post '/contact_settings', to: 'contacts#update_settings'
  end	
  
  resources :contacts
  resources :newsletters

  get '/contact_us', to: 'contacts#new', as: 'contact_us'
  get '/contact_success', to: 'contacts#success', as: 'contact_success'
end

app/models/spree/contact.rb
require 'csv'

module Spree
  class Contact < Spree::Base
    include ActiveModel::Conversion
    include ActiveModel::Validations

    EMAIL_REGEX = /\A
    [^\s@]+ # non-at-sign characters, at least one
    @     # at-sign
    [^\s.@] # non-at-sign and non-period character
    [^\s@]* # 0 or more non-at-sign characters, accepts any number of periods
    \.     # period
    [^\s@]* # 0 or more non-at-sign characters, accepts any number of periods
    [^\s.@] # non-at-sign and non-period character
    \z/x

    validates :email, format: { with: EMAIL_REGEX }, presence: true
    validates :message, presence: true
    validates :firstname, presence: true
    validates :lastname, presence: true

    def deliver_email
      Spree::ContactToolsMailer.contact_email(self).deliver_now
    end

    def self.to_csv
      CSV.generate(headers: true) do |csv|
        csv << [Spree.t('contact_tools.contacts.email'), Spree.t('contact_tools.contacts.firstname'), Spree.t('contact_tools.contacts.lastname'), Spree.t('contact_tools.contacts.phone'), Spree.t('contact_tools.contacts.message')]
        all.each do |contact|
          csv << [contact.email, contact.firstname, contact.lastname, contact.phone, contact.message]
        end
      end
    end
  end
end

app/models/spree/newsletter.rb
require 'csv'

module Spree
  class Newsletter < Spree::Base
    include ActiveModel::Conversion
    include ActiveModel::Validations

    EMAIL_REGEX = /\A
	  [^\s@]+ # non-at-sign characters, at least one
	  @       # at-sign
      [^\s.@] # non-at-sign and non-period character
      [^\s@]* # 0 or more non-at-sign characters, accepts any number of periods
      \.      # period
      [^\s@]* # 0 or more non-at-sign characters, accepts any number of periods
  [^\s.@] # non-at-sign and non-period character
	  \z/x

    validates :email, format: { with: EMAIL_REGEX }, presence: true, uniqueness: true

    def self.to_csv
      CSV.generate(headers: true) do |csv|
        csv << [Spree.t('contact_tools.newsletters.id'), Spree.t('contact_tools.newsletters.email')]
        all.each do |newsletter|
          csv << [newsletter.id, newsletter.email]
        end
      end
    end
  end
end

app/controllers/spree/admin/contacts_controller.rb
require 'recaptcha/rails'

module Spree
  module Admin
    class ContactsController < ResourceController
      def index
        respond_to do |format|
          format.html { Spree::Contact.all }
          format.csv { send_data Spree::Contact.to_csv, filename: "#{Spree.t('contact_tools.contact')}s-#{Date.today}.csv" }
        end
      end

      def delete
        Spree::Contact.find(params[:id]).destroy
        redirect_to :index
      end

      def settings; end

      def update_settings
        Spree::ContactTools.mailer_from = params[:mailer_from]
        Spree::ContactTools.mailer_to = params[:mailer_to]
        Spree::ContactTools.subject = params[:subject] 
        Recaptcha.configuration.site_key = params[:site_key]
        Recaptcha.configuration.secret_key = params[:secret_key]
        flash[:notice] = Spree.t('contact_tools.contacts.admin.settings_success_msg')
        render :settings
      end

      def contact_params
        params.require(:contact).permit(%i[firstname lastname email phone message])
      end
    end
  end
end

app/controllers/spree/admin/newsletters_controller.rb
module Spree
  module Admin
    class NewslettersController < ResourceController
      def index
        respond_to do |format|
          format.html { Spree::Newsletter.all }
          format.csv { send_data Spree::Newsletter.to_csv, filename: "#{Spree.t('contact_tools.newsletter')}-#{Date.today}.csv" }
        end
      end

      def delete
        Spree::Newsletter.find(params[:id]).destroy
        redirect_to :index
      end

      def newsletter_params
        params.require(:newsletter).permit(:email)
      end
    end
  end
end

app/controllers/spree/contacts_controller.rb
require 'recaptcha/rails'

module Spree
  class ContactsController < Spree::StoreController
		def new
			@contact = Spree::Contact.new
   	end
   
		 def create
			@contact = Spree::Contact.new(contact_params)
			verify = Recaptcha.configuration.site_key && Recaptcha.configuration.secret_key ? verify_recaptcha(model: @contact) : true

			if verify   
				if @contact.save
					@contact.deliver_email
					render :success
				else
					render :new
				end
			else
				flash[:error] = Spree.t('contact_tools.contacts.recaptcha_validation_error')
				render :new
			end
   	end
   
		def success; end

		def contact_params
			params.require(:contact).permit(%i[firstname lastname email phone message])
   	end
  end
end

app/controllers/spree/newsletters_controller.rb
module Spree
  class NewslettersController < Spree::StoreController
    def new
      @newsletter = Spree::Newsletter.new
    end

    def create
      @newsletter = Spree::Newsletter.new(newsletter_params)
      if @newsletter.save
        respond_with(@newsletter) do |format| 
          format.json { render json: {"status":"ok","msg":"#{Spree.t('contact_tools.newsletters.success_msg')}"} }
        end
      else
        respond_with(@newsletter) do |format| 
          format.json { render json: {"status":"fail","msg":@newsletter.errors.full_messages.join('\n')} }
        end

      end
    end

    def newsletter_params
      params.require(:newsletter).permit(:email)
    end
  end
end

app/views/spree/admin/contacts/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t('contact_tools.contacts.admin.title') %>
<% end %>

<% content_for :page_actions do %>
	<%= button_link_to Spree.t('contact_tools.contacts.admin.settings'), admin_contact_settings_path, class: 'btn-primary' %>
	<%= button_link_to Spree.t('contact_tools.contacts.admin.export'), admin_contacts_path(format: :csv), id: 'btn-export', class: 'btn-success', icon: 'export' %>
<% end %>

<% if @contacts.any? %>
	<table class='table sortable'>
		<thead>
			<tr data-hook='option_header'>
				<th><%= Spree.t('contact_tools.contacts.admin.email') %></th>
				<th><%= Spree.t('contact_tools.contacts.admin.firstname') %></th>
				<th><%= Spree.t('contact_tools.contacts.admin.lastname') %></th>
				<th><%= Spree.t('contact_tools.contacts.admin.phone') %></th>
				<th><%= Spree.t('contact_tools.contacts.admin.message') %></th>
				<th class='actions'></th>
			</tr>
		</thead>
		<tbody>
			<% @contacts.each do |contact| %>
				<tr class="spree_contact <%= cycle('odd', 'even')%>" id='<%= spree_dom_id contact %>' data-hook='contact-row'>
					<td><%= contact.email %></td>
					<td><%= contact.firstname %></td>
					<td><%= contact.lastname %> </td>
					<td><%= contact.phone %> </td>
					<td><%= contact.message %> </td>
					<td class='actions actions-2 text-right'>
						<%= link_to_delete(contact, no_text: true) %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% else %>
  <div class='alert alert-info no-objects-found'>
    <%= Spree.t(:no_resource_found, resource: Spree.t('contact_tools.contacts.admin.contacts')) %>.
  </div>
<% end %>

app/views/spree/admin/contacts/settings.html.erb
<% content_for :page_title do %>
  <%= Spree.t('contact_tools.contacts.admin.title') %> /
  <%= Spree.t('contact_tools.contacts.admin.settings') %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t('contact_tools.contacts.admin.back_index'), admin_contacts_path, class: 'btn-primary' %>
<% end %>

<div class="ct settings-container">
  <%= form_tag admin_contact_settings_path, method: :post do %>
    <%= content_tag :b, Spree.t('contact_tools.contacts.admin.setting.contact') %>

    <div class="row">
      <div class="col-md-4">
        <%= content_tag :span, Spree.t('contact_tools.contacts.admin.setting.mailer_from') %>
        <%= text_field_tag 'mailer_from', Spree::ContactTools.mailer_from, class: 'form-control' %>
      </div>

      <div class="col-md-4">
        <%= content_tag :span, Spree.t('contact_tools.contacts.admin.setting.mailer_to') %>
        <%= text_field_tag 'mailer_to', Spree::ContactTools.mailer_to, class: 'form-control' %>
      </div>

      <div class="col-md-4">
        <%= content_tag :span, Spree.t('contact_tools.contacts.admin.setting.subject') %>
        <%= text_field_tag 'subject', Spree::ContactTools.subject, class: 'form-control' %>
      </div>
    </div>

    <%= content_tag :b, Spree.t('contact_tools.contacts.admin.setting.recaptcha') %>
    
    <%= content_tag :span, Spree.t('contact_tools.contacts.admin.setting.recaptcha_instructions'), class: 'instructions' %>

    <div class="row">
      <div class="col-md-6">
        <%= content_tag :span, Spree.t('contact_tools.contacts.admin.setting.site_key')  %>
        <%= text_field_tag 'site_key', Recaptcha.configuration.site_key, class: 'form-control' %>
      </div>

      <div class="col-md-6">
        <%= content_tag :span, Spree.t('contact_tools.contacts.admin.setting.secret_key') %>
        <%= text_field_tag 'secret_key', Recaptcha.configuration.secret_key, class: 'form-control' %>
      </div>
    </div>
    
    <div class="button">
      <%= submit_tag Spree.t('contact_tools.contacts.admin.setting.update'), class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/spree/admin/newsletters/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t('contact_tools.newsletters.admin.title') %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t('contact_tools.newsletters.admin.export'), admin_newsletters_path(format: :csv), id: 'btn-export', class: 'btn-primary' %>
<% end %>

<% if @newsletters.any? %>
  <table class='table sortable'>
    <thead>
      <tr data-hook='option_header'>
        <th><%= Spree.t('contact_tools.newsletters.admin.email') %></th>
      </tr>
    </thead>
    <tbody>
      <% @newsletters.each do |newsletter| %>
        <tr class="spree_newsletter <%= cycle('odd', 'even')%>" id="<%= spree_dom_id newsletter %>" data-hook="option_row">
          <td><%= newsletter.email %></td>
          <td class="actions actions-2 text-right">
            <%= link_to_delete(newsletter, no_text: true) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: Spree.t('contact_tools.newsletters.admin.newsletters')) %>
  </div>
<% end %>

app/views/spree/admin/shared/_user_and_contact_tools.html.erb
<ul class="nav nav-sidebar border-bottom">
  <%= main_menu_tree Spree.t('contact_tools.users.admin.users'), icon: 'user', url: '#sidebar-user', sub_menu: 'users' %>
</ul>

app/views/spree/admin/shared/sub_menu/_users.html.erb
<ul id="sidebar-user" class="border-top bg-white nav nav-pills nav-stacked collapse" data-hook="admin_user_sub_tabs">
  <%= tab :users, label: Spree.t('contact_tools.users.admin.users') %>
  <%= tab :contacts, label: Spree.t('contact_tools.contacts.admin.contacts') %>
  <%= tab :newsletters, label: Spree.t('contact_tools.newsletters.admin.newsletters') %>
</ul>

app/views/spree/contacts/new.html.erb
<div class="ct contacts-container">
	<%= content_tag :h1, Spree.t('contact_tools.contacts.title') %>
	
	<div class="form-container">
		<div class="instructions">
			<%= content_tag :span, Spree.t('contact_tools.contacts.instructions') %>
		</div>

		<%= form_for @contact do |f| %>
			<div class="field firstname">
				<%= f.label "#{Spree.t('contact_tools.contacts.firstname')} *", class: 'required' %>
				<%= f.text_field :firstname %>
			</div>

			<div class="field lastname">
				<%= f.label "#{Spree.t('contact_tools.contacts.lastname')} *", class: 'required' %>
				<%= f.text_field :lastname %>
			</div>

			<div class="field phone">
				<%= f.label Spree.t('contact_tools.contacts.phone') %>
				<%= f.text_field :phone %>
			</div>

			<div class="field email">
				<%= f.label "#{Spree.t('contact_tools.contacts.email')} *", class: 'required' %>
				<%= f.text_field :email %>
			</div>

			<div class="field message">
				<%= f.label "#{Spree.t('contact_tools.contacts.message')} *", class: 'required' %>
				<%= f.text_area :message %>
			</div>

			<% if Recaptcha.configuration.site_key && Recaptcha.configuration.secret_key %>
				<div class="recaptcha-tags">
					<div class="box">
						<%= recaptcha_tags %>
					</div>
				</div>
			<% end %>

			<div class="button">
				<%= button_tag Spree.t('contact_tools.contacts.send'), type: :submit, class: 'btn btn-success' %>
			</div>
		<% end %>
	</div>
</div>

app/views/spree/contacts/success.html.erb
<div class="ct contacts-container">
	<div class="success-msg">
		<%= content_tag :span, Spree.t('contact_tools.contacts.success_msg') %>
		<%= link_to Spree.t('contact_tools.contacts.back_home'), spree.root_path %> 
	</div>
</div>

app/views/spree/shared/_newsletter.html.erb
<div class="ct newsletters-container">
  <%= form_for Spree::Newsletter.new, html: { id: form_id = form_id || 'new_newsletter_form', onsubmit: "submitNewsletter(event, '##{form_id}');" } do |f| %>
    <%= content_tag :div, class: "#{div_class = div_class || 'form-container'}" do %>
      <%= f.text_field :email, class: input_class = input_class || 'field email', placeholder: placeholder_text = placeholder_text || Spree.t('contact_tools.newsletters.template.placeholder') %> 

      <button type="submit" class="<%= button_class = button_class || 'button' %>">
        <%= button_text = button_text || Spree.t('contact_tools.newsletters.template.button_text') %>
      </button>
    <% end %>
  <% end %>
</div>